CREATE DATABASE ReparacionesSC
GO
USE ReparacionesSC
GO

CREATE TABLE Usuarios
(
	UsuarioID INT PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL,
	CorreoElectronico VARCHAR(50),
	Telefono VARCHAR(15) UNIQUE
)
GO

CREATE TABLE Tecnicos
(
	TecnicoID INT PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50),
	Especialidad VARCHAR(50)
)
GO

CREATE TABLE Equipos
(
	EquipoID INT PRIMARY KEY IDENTITY(1,1),
	TipoEquipo VARCHAR(50) NOT NULL,
	Modelo VARCHAR(50),
	UsuarioID INT
	CONSTRAINT fk_EquiposUsuarioID FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID)
)
GO

CREATE TABLE Reparaciones
(
	ReparacionID INT PRIMARY KEY IDENTITY(1,1),
	EquipoID INT,
	FechaSolicitud DATETIME DEFAULT GETDATE(),
	Estado CHAR(1),
	CONSTRAINT fk_ReparacionesEquipoID FOREIGN KEY (EquipoID) REFERENCES Equipos(EquipoID)
)
GO

CREATE TABLE Asignaciones
(
	AsignacionID INT PRIMARY KEY IDENTITY(1,1),
	ReparacionID INT,
	TecnicooID INT,
	FechaAsignacion DATETIME DEFAULT GETDATE(),
	CONSTRAINT fk_AsignacionesReparacionID FOREIGN KEY (ReparacionID) REFERENCES Reparaciones(ReparacionID),
	CONSTRAINT fk_AsignacionesTecnicoID FOREIGN KEY (TecnicooID) REFERENCES Tecnicos(TecnicoID)
)
GO

CREATE TABLE DetallesReparacion
(
	DetalleID INT PRIMARY KEY IDENTITY(1,1),
	ReparacionID INT,
	Descripcion VARCHAR(50),
	FechaInicio DATETIME DEFAULT GETDATE(),
	FechaFin DATETIME,
	CONSTRAINT fk_DetallesReparacionID_ReparacionID FOREIGN KEY (ReparacionID) REFERENCES Reparaciones(ReparacionID)
)
GO

INSERT INTO Usuarios(Nombre, CorreoElectronico, Telefono) VALUES 
('Mario', 'mario@soto.com', '24448793'), 
('Luis', 'luis@perez.com', '24943528'), 
('Pedro', 'pedro@sanchez.com', '85590520')
GO

INSERT INTO Tecnicos(Nombre, Especialidad) VALUES 
('Ignacio', 'Reparacion de Software'), 
('Manfren', 'Reparacion de Hardware')
GO

INSERT INTO Equipos(TipoEquipo, Modelo, UsuarioID) VALUES
('Computadora Escritorio', 'Armada', 1),
('Portatil', 'Lenovo', 2),
('Monitor', 'ASUS', 3)
GO

INSERT INTO Reparaciones(EquipoID, Estado) VALUES
(1, 'a'),
(2, 'b'),
(3, 'c')
GO

INSERT INTO Asignaciones(ReparacionID, TecnicooID) VALUES
(1, 1),
(2, 1),
(3, 2)
GO

INSERT INTO DetallesReparacion(ReparacionID, Descripcion) VALUES
(1, 'Cambiar pasta termica y Limpieza')
GO

CREATE PROCEDURE CONSULTAR_USUARIOS
AS
	BEGIN
		SELECT * FROM Usuarios
	END
GO

CREATE PROCEDURE CONSULTAR_USUARIOS_ID
@ID INT
AS
	BEGIN
		SELECT * FROM Usuarios WHERE UsuarioID = @ID
	END
GO

CREATE PROCEDURE BORRAR_USUARIOS_ID
@ID INT
AS
	BEGIN
		DELETE Usuarios WHERE UsuarioID = @ID
	END
GO

CREATE PROCEDURE INSERTAR_USUARIO
@NOMBRE VARCHAR(50),
@CORREO VARCHAR(50),
@TELEFONO VARCHAR(15)
AS
	BEGIN
		INSERT INTO Usuarios(Nombre, CorreoElectronico, Telefono) VALUES (@NOMBRE, @CORREO, @TELEFONO)
	END
GO

CREATE PROCEDURE ACTUALIZAR_USUARIO_ID
@ID INT,
@NOMBRE VARCHAR(50),
@CORREO VARCHAR(50),
@TELEFONO VARCHAR(15)
AS
	BEGIN
		UPDATE Usuarios SET Nombre = @NOMBRE, CorreoElectronico = @CORREO, Telefono = @TELEFONO WHERE UsuarioID = @ID
	END
GO

CREATE PROCEDURE CONSULTAR_TECNICOS
AS
	BEGIN
		SELECT * FROM Tecnicos
	END
GO

CREATE PROCEDURE CONSULTAR_TECNICOS_ID
@ID INT
AS
	BEGIN
		SELECT * FROM Tecnicos WHERE TecnicoID = @ID
	END
GO

CREATE PROCEDURE BORRAR_TECNICOS_ID
@ID INT
AS
	BEGIN
		DELETE Tecnicos WHERE TecnicoID = @ID
	END
GO

CREATE PROCEDURE INSERTAR_TECNICO
@NOMBRE VARCHAR(50),
@ESPECIALIDAD VARCHAR(50)
AS
	BEGIN
		INSERT INTO Tecnicos(Nombre, Especialidad) VALUES (@NOMBRE, @ESPECIALIDAD)
	END
GO

CREATE PROCEDURE ACTUALIZAR_TECNICO_ID
@ID INT,
@NOMBRE VARCHAR(50),
@ESPECIALIDAD VARCHAR(50)
AS
	BEGIN
		UPDATE Tecnicos SET Nombre = @NOMBRE, Especialidad = @ESPECIALIDAD WHERE TecnicoID = @ID
	END
GO

CREATE PROCEDURE CONSULTAR_EQUIPOS
AS
	BEGIN
		SELECT * FROM Equipos
	END
GO

CREATE PROCEDURE CONSULTAR_EQUIPOS_ID
@ID INT
AS
	BEGIN
		SELECT * FROM Equipos WHERE EquipoID = @ID
	END
GO

CREATE PROCEDURE BORRAR_EQUIPOS_ID
@ID INT
AS
	BEGIN
		DELETE Equipos WHERE EquipoID = @ID
	END
GO

CREATE PROCEDURE INSERTAR_EQUIPO
@TIPOEQUIPO VARCHAR(50),
@MODELO VARCHAR(50),
@USUARIOID INT
AS
	BEGIN
		INSERT INTO Equipos(TipoEquipo, Modelo, UsuarioID) VALUES (@TIPOEQUIPO, @MODELO, @USUARIOID)
	END
GO

CREATE PROCEDURE ACTUALIZAR_EQUIPOO_ID
@ID INT,
@TIPOEQUIPO VARCHAR(50),
@MODELO VARCHAR(50),
@USUARIOID INT
AS
	BEGIN
		UPDATE Equipos SET TipoEquipo = @TIPOEQUIPO, Modelo = @MODELO, UsuarioID = @USUARIOID WHERE EquipoID = @ID
	END
GO